project:
  type: default

university: "UNIVERSIDAD NACIONAL DE LOJA"
faculty: "FACULTAD JURÍDICA, SOCIAL Y ADMINISTRATIVA"
school: "CARRERA DE ECONOMÍA"
course: "ECONOMÍA DE LA INNOVACIÓN"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    pdf-engine: lualatex
    template: /home/erick-fcs/Capital_Workstation/capital-workstation-libs/src/ecs_quantitative/reporting/templates/academic_task.tex
    toc: false
    number-sections: true
    citeproc: true
  docx:
    toc: true
    number-sections: true

execute:
  echo: false
  warning: false

bibliography: 
  - /home/erick-fcs/Capital_Workstation/capital-workstation-libs/src/ecs_quantitative/reporting/assets/references.bib
csl: /home/erick-fcs/Capital_Workstation/capital-workstation-libs/src/ecs_quantitative/reporting/templates/apa_7.csl
